-- H18: Seed all compliance items from master list in spec

INSERT INTO compliance_items (category, jurisdiction, title, description, priority, frequency, estimated_cost, where_to_go, how_to_complete, ai_help_prompt) VALUES

-- BUSINESS REGISTRATION
('business_registration', 'ohio_state', 'Ohio LLC Registration',
 'AK Renovations LLC must be registered with the Ohio Secretary of State',
 'critical', 'one_time', '$99 filing fee',
 'https://www.ohiosos.gov/businesses/business-filings/',
 '1. Go to Ohio SOS website 2. File Articles of Organization 3. Choose LLC 4. Pay $99 fee 5. Receive Certificate of Organization',
 'Help me register AK Renovations LLC with the Ohio Secretary of State. Walk me through each step.'),

('business_registration', 'ohio_state', 'Ohio Registered Agent',
 'Ohio LLCs must maintain a registered agent with an Ohio address',
 'critical', 'annual', '$0-$150/year',
 'https://www.ohiosos.gov',
 'Can be Adam personally (if Ohio resident) or a registered agent service',
 'Explain what a registered agent is and whether Adam needs to hire one or can serve as his own.'),

('business_registration', 'ohio_state', 'Ohio Operating Agreement',
 'Written operating agreement defining LLC ownership and operations',
 'high', 'one_time', '$0 (DIY) or $300-500 (attorney)',
 'Internal document — not filed with state',
 'Draft an operating agreement or have attorney prepare one',
 'Generate a basic single-member LLC operating agreement for AK Renovations.'),

('business_registration', 'summit_county', 'Summit County Business Registration',
 'Register the business with Summit County Fiscal Office',
 'high', 'one_time', '$25-50',
 'https://fiscal.summitoh.net',
 'Register trade name/DBA if operating as AK Renovations (not the LLC legal name)',
 'Help me register AK Renovations as a trade name in Summit County Ohio.'),

-- TAX REGISTRATIONS
('tax', 'federal', 'Federal EIN (Employer Identification Number)',
 'Required for business banking, payroll, and tax filing. Like a SSN for your business.',
 'critical', 'one_time', '$0',
 'https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online',
 'Apply online at IRS.gov — takes 15 minutes, EIN issued immediately',
 'Walk me through applying for a Federal EIN for AK Renovations LLC.'),

('tax', 'ohio_state', 'Ohio Commercial Activity Tax (CAT) Registration',
 'Ohio businesses with over $150,000 gross receipts must register for CAT',
 'critical', 'annual', '$0 registration, tax varies',
 'https://gateway.ohio.gov',
 'Register through Ohio Business Gateway',
 'Help me register for Ohio Commercial Activity Tax for AK Renovations.'),

('tax', 'ohio_state', 'Ohio Withholding Tax Account',
 'Required to withhold and remit Ohio income tax from employee wages',
 'critical', 'quarterly', '$0 registration',
 'https://gateway.ohio.gov',
 'Register as employer through Ohio Business Gateway',
 'Help me set up Ohio employer withholding tax account.'),

('tax', 'federal', 'Federal Quarterly Estimated Taxes (Self-Employment)',
 'As S-corp owner, Adam pays quarterly estimated taxes on distributions and salary',
 'high', 'quarterly', 'Varies — typically 25-30% of net profit',
 'https://www.irs.gov/businesses/small-businesses-self-employed/estimated-taxes',
 'Calculate using Form 1040-ES, pay via IRS Direct Pay',
 'Calculate my estimated quarterly tax payment based on current revenue and expenses.'),

('tax', 'ohio_state', 'Ohio S-Corporation Election',
 'If operating as S-corp, file Ohio form IT 4708 or IT 1140',
 'high', 'annual', '$0',
 'https://tax.ohio.gov',
 'File Ohio pass-through entity tax forms annually',
 'Explain the Ohio S-corp tax filing requirements for AK Renovations.'),

-- LICENSING
('licensing', 'ohio_state', 'Ohio Contractor License (HIC)',
 'Ohio Home Improvement Contractor license required for residential work over $1,000',
 'critical', 'biennial', '$200 biennial renewal',
 'https://www.com.ohio.gov/dico/contractor/',
 '1. Complete application 2. Provide proof of insurance 3. Pay fee 4. Pass background check',
 'Help me apply for or renew my Ohio Home Improvement Contractor license.'),

('licensing', 'ohio_state', 'Ohio Construction Industry Licensing Board (CILB)',
 'Required for commercial work — check if any projects qualify',
 'medium', 'annual', 'Varies by license type',
 'https://www.com.ohio.gov/dico/',
 'Review project types to determine if CILB license is needed',
 'Do I need an Ohio CILB license for the type of work AK Renovations does?'),

-- INSURANCE
('insurance', 'ohio_state', 'Ohio Workers Compensation (BWC)',
 'Mandatory for all W-2 employees in Ohio. Cannot legally have employees without this.',
 'critical', 'annual', '$800-2,500/year depending on payroll and classification',
 'https://www.bwc.ohio.gov',
 '1. Register at BWC.ohio.gov 2. Get employer account 3. Pay premiums based on payroll',
 'Help me register AK Renovations with Ohio Bureau of Workers Compensation.'),

('insurance', 'other', 'General Liability Insurance',
 'Minimum $1M per occurrence, $2M aggregate. Required by most subs and clients.',
 'critical', 'annual', '$2,000-4,000/year for a contractor at this revenue level',
 'Contact insurance broker — Westfield, Erie, or Frankenmuth recommended for Ohio contractors',
 'Get quotes from 3 brokers. Specify: residential renovation, $1.5M-2M revenue, 2 employees',
 'What should I look for in a general liability policy for a residential renovation contractor in Ohio?'),

('insurance', 'other', 'Commercial Auto Insurance',
 'Required for any vehicle used for business purposes',
 'critical', 'annual', '$1,500-2,500/year per vehicle',
 'Same broker as GL — often bundled for discount',
 'Add commercial auto to GL policy or get separate policy',
 'Do I need commercial auto insurance for my trucks used on job sites?'),

('insurance', 'other', 'Builder Risk Insurance (Per Project)',
 'Required for addition and new construction projects over $100K',
 'high', 'as_needed', '$500-1,500 per project depending on value',
 'Your GL broker or Markel/Philadelphia Insurance for builders risk',
 'Get builder risk quote for each addition project at contract signing',
 'Explain builder risk insurance and when AK Renovations needs it.'),

('insurance', 'other', 'Umbrella / Excess Liability',
 'Additional liability coverage above GL limits — recommended at $1-2M revenue',
 'medium', 'annual', '$500-1,000/year for $1M umbrella',
 'Same broker as GL',
 'Add umbrella policy on top of existing GL',
 'Does AK Renovations need an umbrella liability policy?'),

-- EMPLOYMENT
('employment', 'federal', 'Federal I-9 Employment Eligibility Verification',
 'Required for every new hire. Must verify identity and work authorization.',
 'critical', 'as_needed', '$0',
 'https://www.uscis.gov/i-9',
 'Complete I-9 within 3 days of each new hire start date. Keep on file.',
 'Walk me through the I-9 process for a new employee.'),

('employment', 'federal', 'Federal W-4 Employee Withholding',
 'Every employee must complete a W-4 before first paycheck',
 'critical', 'as_needed', '$0',
 'https://www.irs.gov/forms-pubs/about-form-w-4',
 'Have each new employee complete Form W-4 on or before first day',
 'Generate a checklist for new employee paperwork at AK Renovations.'),

('employment', 'ohio_state', 'Ohio New Hire Reporting',
 'Must report every new hire to Ohio within 20 days of hire date',
 'critical', 'as_needed', '$0',
 'https://oh.newhirereporting.com',
 'Report online within 20 days of each new hire',
 'Help me report a new hire to Ohio.'),

('employment', 'federal', 'Payroll Service Setup (Gusto)',
 'Automated payroll, tax filing, W-2s, and direct deposit for Jeff and Steven',
 'critical', 'monthly', '$40/mo base + $6/employee',
 'https://gusto.com',
 '1. Sign up at Gusto 2. Connect bank account 3. Add employees 4. Set pay schedule',
 'Help me set up Gusto payroll for AK Renovations with two employees.'),

('employment', 'ohio_state', 'Ohio Unemployment Insurance (UI) Account',
 'Required as an employer in Ohio — fund unemployment benefits for laid-off employees',
 'critical', 'quarterly', '~2.7% of wages for new employers',
 'https://unemploymenthelp.ohio.gov/employers',
 'Register online through Ohio Job & Family Services',
 'Help me register for Ohio Unemployment Insurance as an employer.'),

('employment', 'federal', 'OSHA Safety Program',
 'Written safety program required for construction employers in Ohio',
 'high', 'annual', '$0 (DIY) or $500-1,000 (consultant)',
 'https://www.osha.gov/small-business',
 'Create written safety plan covering: fall protection, PPE, tool safety, hazcom',
 'Generate a basic OSHA safety program for a residential renovation contractor with 2 employees.'),

('employment', 'other', 'Employee Handbook',
 'Written policies for: PTO, vehicle use, tool policy, drug testing, termination',
 'high', 'one_time', '$0 (DIY) or $300-500 (HR consultant)',
 'Internal document',
 'Draft handbook covering Ohio-specific requirements',
 'Generate an employee handbook for AK Renovations covering Ohio requirements.'),

-- BANKING & FINANCIAL
('banking', 'federal', 'Business Checking Account',
 'Separate business bank account required. Never comingle personal and business funds.',
 'critical', 'one_time', '$0-25/month',
 'Relay Bank (relay.fi) — recommended for small business, free, built-in expense tracking',
 '1. Open at relay.fi 2. Use EIN (not SSN) 3. Set up operating account',
 'What should I look for in a business bank account for AK Renovations?'),

('banking', 'federal', 'Business Tax Reserve Account',
 'Separate account to hold quarterly tax payments — prevents spending tax money',
 'high', 'one_time', '$0',
 'Same bank as operating account — open as second account',
 'Transfer 25-30% of every client payment into this account immediately',
 'How much should I set aside in my tax reserve account based on current revenue?'),

('banking', 'federal', 'Business Credit Card',
 'Dedicated card for materials and business expenses — builds credit, earns rewards',
 'high', 'one_time', '$0-95/year',
 'Home Depot Pro Xtra card + general business card (Chase Ink or Capital One Spark)',
 'Apply with EIN once business is registered',
 'What business credit cards make the most sense for a renovation contractor?'),

('banking', 'federal', 'Business Line of Credit',
 'Credit line for cash flow gaps between milestone payments. Critical at this project size.',
 'high', 'one_time', 'Interest only when drawn',
 'Your business bank or a local credit union in Summit County',
 'Apply after 6-12 months of business banking history',
 'Help me prepare a business line of credit application for AK Renovations.'),

-- WEBSITE & DIGITAL
('website_digital', 'other', 'Website Launch — akrenovationsohio.com',
 'Website must be live for Google Ads, SEO, and credibility with clients',
 'critical', 'one_time', 'Domain registered at Porkbun',
 'akrenovationsohio.com (registered)',
 'Build and launch — this is already in progress',
 'What pages does AK Renovations website need at minimum?'),

('website_digital', 'other', 'Google Business Profile Optimization',
 'Complete GBP with photos, hours, services, and active review responses',
 'high', 'as_needed', '$0',
 'https://business.google.com',
 'Add 10+ photos, complete all fields, respond to every review within 24 hours',
 'Help me write a response to this Google review for AK Renovations.'),

('website_digital', 'other', 'Google Local Service Ads Verification',
 'Google background check and license verification for LSA badge',
 'high', 'annual', '$0 to verify, pay per lead',
 'https://ads.google.com/local-services-ads',
 'Submit license, insurance, and background check through Google',
 'Walk me through the Google Local Service Ads verification process for a contractor.'),

('website_digital', 'federal', 'Privacy Policy & Terms of Service',
 'Required on website if collecting any user data (contact forms, etc.)',
 'medium', 'one_time', '$0 (generated) or $300-500 (attorney)',
 'Website pages',
 'Generate privacy policy and terms of service for the website',
 'Generate a privacy policy and terms of service for akrenovationsohio.com.'),

-- CONTRACTS & LEGAL
('contracts', 'ohio_state', 'Client Contract Template — Attorney Review',
 'Standard client contract reviewed by Ohio construction attorney',
 'high', 'one_time', '$500-1,000 attorney review',
 'Ohio construction attorney — find via Ohio State Bar Association',
 'Generate contract template, have attorney review, finalize',
 'What should be in a residential renovation contract in Ohio?'),

('contracts', 'ohio_state', 'Subcontractor Agreement Template — Attorney Review',
 'Standard sub agreement reviewed by Ohio construction attorney',
 'high', 'one_time', 'Covered by same attorney review as client contract',
 'Same attorney as client contract',
 'Generate sub agreement template (AK Ops does this), have attorney review',
 'Generate a subcontractor agreement template for AK Renovations.'),

('contracts', 'ohio_state', 'Mechanic Lien Process Document',
 'Written process for filing mechanic liens in Ohio on non-paying clients',
 'high', 'one_time', '$0 (documented process) + filing fees if needed',
 'Ohio Revised Code Chapter 1311',
 'Document the lien process: notice requirements, deadlines, filing steps',
 'Explain the Ohio mechanic lien process and deadlines for a residential contractor.')

ON CONFLICT DO NOTHING;
