-- C13: Supabase Storage bucket 'documents' with RLS
-- NOTE: Storage bucket creation requires Supabase Dashboard or CLI.
-- Run: supabase storage buckets create documents --private
-- The policies below apply once the bucket exists.

-- Admin has full access to all documents
-- Clients can read only their own project documents via signed URLs (generated server-side)
-- All writes go through edge functions with service role key

-- This migration documents the required bucket configuration:
-- Bucket name: documents
-- Public: false (private)
-- File size limit: 50MB
-- Allowed MIME types: application/pdf, image/jpeg, image/png, image/webp

-- Storage RLS policies (applied via Supabase dashboard or via storage API):
-- Policy 1: "Admin full access" - role=admin → SELECT, INSERT, UPDATE, DELETE
-- Policy 2: "Service role writes" - authenticated service role → INSERT, UPDATE
-- Signed URLs (1hr expiry) generated by edge functions for client downloads

COMMENT ON TABLE invoices IS 'PDF stored at: documents/invoices/{id}.pdf and documents/invoices/{id}-paid.pdf';
COMMENT ON TABLE proposals IS 'PDF stored at: documents/proposals/{id}.pdf';
COMMENT ON TABLE contracts IS 'PDF stored at: documents/contracts/{id}.pdf and documents/contracts/{id}-signed.pdf';
